<a href="https://colab.research.google.com/github/D0H00N/DL/blob/main/3_%EA%B7%B8%EB%9E%98%EB%94%94%EC%96%B8%ED%8A%B8%ED%85%8C%EC%9D%B4%ED%94%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 그레디언트테이프 = 자동 미분 기능 활용 API
사용 python with 문, 코드 블록 안의 모든 텐서 연산을 계산 그래프 형태로 기록

In [4]:
import tensorflow as tf

#1. scala 값의 기울기 계산

x = tf.Variable(0.)

with tf.GradientTape() as tape:
#y를 계산하기 위한 규칙
  y = 2*x + 3

grad_y_x = tape.gradient(y,x)
grad_y_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [5]:
#2. 행렬의 기울기 계산

x = tf.Variable( tf.zeros((2,2)) )
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [6]:
with tf.GradientTape() as tape:
  y = 2*x + 3

grad_y_x = tape.gradient(y, x)
grad_y_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [11]:
#3. 선형함수의 기울기 w 계산

#가중치 = 기울기
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros(2,))

x = tf.random.uniform((2,2))
with tf.GradientTape() as tape:
  y = tf.matmul(x, W) + b  # W*x 선형함수식 , 점곱합수

grad_y_x_b = tape.gradient(y, [W,b] ) # 편미분
grad_y_x_b # 2개 텐서 담긴 리스트

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.8373891, 0.8373891],
        [1.8033402, 1.8033402]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]